# POV-Ray core + VFE, built as a single static library on Linux.
#
# Prototype build glue for embedding POV-Ray's VFE (Virtual Front End) API
# into bpp instead of shelling out to the povray executable. Linux twin of
# povray-mingw/povvfe.pro -- see povray-linux/README.md for the full build
# steps.
#
# Reuses the same source file lists as povray-mingw/povvfe.pro, but swaps
# the Windows platform/vfe glue for POV-Ray's Unix equivalents:
# platform/windows/{osversioninfo,syspovfilesystem,syspovpath,syspovtask,
# syspovtimer}.cpp -> platform/unix/{syspovfilesystem,syspovtimer}.cpp
# (POV-Ray's generic source/base/path.cpp and source/backend/support/task.cpp
# defaults cover what syspovpath.cpp/syspovtask.cpp override on Windows --
# see unix/povconfig/syspovconfigbase.h and syspovconfigbackend.h -- and
# osversioninfo.cpp has no callers outside platform/windows/), and
# vfe/win/vfeplatform.cpp -> vfe/unix/vfeplatform.cpp + vfe/unix/unixoptions.cpp
# (vfe/unix/unixconsole.cpp is excluded -- it's a console main(), not needed
# here, same reasoning povvfe.pro applies to excluding source/povmain.cpp).
#
# Unlike the Windows build (whose syspovconfig_mingw32.h never defines
# BUILD_X86), unix/povconfig/syspovconfig.h defines BUILD_X86 unconditionally
# on x86_64 (from unix/config.h) and requires platform/x86/cpuid.cpp
# (POV_CPUINFO) -- same as the real unix/Makefile.am's `if BUILD_x86` block.
#
# syspovconfig.h also unconditionally sets TRY_OPTIMIZED_NOISE_AVX/AVXFMA4/
# AVX2FMA3 for any GCC >= 4.6/4.5/4.7 (a compiler-version check, independent
# of what ISA flags this translation unit is actually compiled with), which
# makes platform/x86/optimizednoise.cpp's gaOptimizedNoiseInfo[] table
# (referenced by source/core/material/noise.cpp) pull in extern
# AVXNoise/AVXFMA4Noise/AVX2FMA3Noise symbols unconditionally too. The real
# unix/Makefile.am builds each ISA's noise code as its own tiny static lib
# with just that ISA's flags (libx86avx.a with -mavx, libx86avxfma4.a with
# -mavx -mfma4, libx86avx2fma3.a with -mavx2 -mfma), so the bulk of the
# binary stays on the generic baseline and only those specific functions
# require the extra instruction sets, selected at runtime via CPUInfo
# feature detection. This matters beyond portability: giving the *whole*
# target -mfma4, for instance, lets GCC's optimizer emit FMA4 instructions
# in any translation unit, not just the one CPUInfo-gated call site -- and
# FMA4 is AMD-only (Bulldozer-era), so that SIGILLs immediately on any
# non-FMA4 CPU the moment such code runs, runtime dispatch or not. The
# QMAKE_EXTRA_COMPILERS blocks below reproduce the real per-file ISA-flag
# split for exactly this reason, not just for style.
#
# Built as one combined archive rather than mirroring the core/vfe project
# split: core and vfe are circularly dependent (see unix/prebuild.sh), and a
# single archive sidesteps GNU ar/ld link-order problems entirely.
#
# qmake derives object file names from source basenames and silently drops
# a SOURCES entry instead of erroring when it thinks two entries collide --
# both on an exact basename match (source/povms/povms.c vs povms.cpp) and,
# apparently, a basename-suffix match (source/core/material/portablenoise.cpp
# vs platform/x86/avx/avxportablenoise.cpp). povms_c_shim.cpp and
# portablenoise_shim.cpp work around this by #include-ing the real .cpp
# under a non-colliding name.

TEMPLATE = lib
CONFIG += staticlib c++11 warn_off debug_and_release
CONFIG -= qt
TARGET = povvfe

CONFIG(debug, debug|release) {
  DESTDIR = debug
} else {
  DESTDIR = release
}
OBJECTS_DIR = $$DESTDIR/.obj

# unix/povconfig/syspovconfig.h #errors without this: it expects unix/config.h
# (already generated by the sibling checkout's ./configure) on the include path.
DEFINES += HAVE_CONFIG_H
DEFINES += BUILT_BY=\\\"bpp-povvfe-prototype\\\"
DEFINES += BOOST_BIND_GLOBAL_PLACEHOLDERS

POVRAY = $$PWD/../../povray

INCLUDEPATH += \
    $$POVRAY/source \
    $$POVRAY/vfe \
    $$POVRAY/vfe/unix \
    $$POVRAY/platform/unix \
    $$POVRAY/platform \
    $$POVRAY/platform/x86 \
    $$POVRAY/unix \
    $$POVRAY/unix/povconfig

CONFIG += link_pkgconfig
PKGCONFIG += zlib libpng libjpeg libtiff-4

QMAKE_CXXFLAGS += -std=gnu++11

LIBS += -lpthread

# The AVX/AVX2/FMA3/FMA4 noise implementations each need their own ISA
# flags -- and *only* their own translation unit compiled with them,
# mirroring the real unix/Makefile.am's libx86avx.a/libx86avxfma4.a/
# libx86avx2fma3.a split (see the comment near the top of this file). This
# matters beyond style: giving the whole target -mfma4, for example, lets
# GCC's optimizer legally emit FMA4 instructions in *any* translation unit
# it likes, not just the one CPUInfo-gated call site -- and FMA4 is AMD-only
# (Bulldozer-era), so that instantly SIGILLs on any Intel CPU (or any CPU
# without FMA4) the moment such code runs, regardless of the runtime
# dispatch these noise implementations are supposed to be gated behind.
avx_noise_compiler.name = avx noise compiler
avx_noise_compiler.input = AVX_NOISE_SOURCES
avx_noise_compiler.output = $$OBJECTS_DIR/${QMAKE_FILE_IN_BASE}$${first(QMAKE_EXT_OBJ)}
avx_noise_compiler.commands = $(CXX) -c $(CXXFLAGS) -mavx $(INCPATH) -o ${QMAKE_FILE_OUT} ${QMAKE_FILE_IN}
avx_noise_compiler.CONFIG += no_link
avx_noise_compiler.variable_out = OBJECTS
QMAKE_EXTRA_COMPILERS += avx_noise_compiler
AVX_NOISE_SOURCES += \
    $$POVRAY/platform/x86/avx/avxnoise.cpp \
    $$POVRAY/platform/x86/avx/avxportablenoise.cpp

avxfma4_noise_compiler.name = avx/fma4 noise compiler
avxfma4_noise_compiler.input = AVXFMA4_NOISE_SOURCES
avxfma4_noise_compiler.output = $$OBJECTS_DIR/${QMAKE_FILE_IN_BASE}$${first(QMAKE_EXT_OBJ)}
avxfma4_noise_compiler.commands = $(CXX) -c $(CXXFLAGS) -mavx -mfma4 $(INCPATH) -o ${QMAKE_FILE_OUT} ${QMAKE_FILE_IN}
avxfma4_noise_compiler.CONFIG += no_link
avxfma4_noise_compiler.variable_out = OBJECTS
QMAKE_EXTRA_COMPILERS += avxfma4_noise_compiler
AVXFMA4_NOISE_SOURCES += $$POVRAY/platform/x86/avxfma4/avxfma4noise.cpp

avx2fma3_noise_compiler.name = avx2/fma3 noise compiler
avx2fma3_noise_compiler.input = AVX2FMA3_NOISE_SOURCES
avx2fma3_noise_compiler.output = $$OBJECTS_DIR/${QMAKE_FILE_IN_BASE}$${first(QMAKE_EXT_OBJ)}
avx2fma3_noise_compiler.commands = $(CXX) -c $(CXXFLAGS) -mavx2 -mfma $(INCPATH) -o ${QMAKE_FILE_OUT} ${QMAKE_FILE_IN}
avx2fma3_noise_compiler.CONFIG += no_link
avx2fma3_noise_compiler.variable_out = OBJECTS
QMAKE_EXTRA_COMPILERS += avx2fma3_noise_compiler
AVX2FMA3_NOISE_SOURCES += $$POVRAY/platform/x86/avx2fma3/avx2fma3noise.cpp

SOURCES += \
    $$POVRAY/platform/unix/syspovfilesystem.cpp \
    $$POVRAY/platform/unix/syspovtimer.cpp \
    $$POVRAY/platform/x86/cpuid.cpp \
    $$POVRAY/platform/x86/optimizednoise.cpp \
    $$POVRAY/source/backend/bounding/boundingtask.cpp \
    $$POVRAY/source/backend/control/benchmark.cpp \
    $$POVRAY/source/backend/control/benchmark_ini.cpp \
    $$POVRAY/source/backend/control/benchmark_pov.cpp \
    $$POVRAY/source/backend/control/messagefactory.cpp \
    $$POVRAY/source/backend/control/parsertask.cpp \
    $$POVRAY/source/backend/control/renderbackend.cpp \
    $$POVRAY/source/backend/control/scene.cpp \
    $$POVRAY/source/backend/lighting/photonestimationtask.cpp \
    $$POVRAY/source/backend/lighting/photonshootingstrategy.cpp \
    $$POVRAY/source/backend/lighting/photonshootingtask.cpp \
    $$POVRAY/source/backend/lighting/photonsortingtask.cpp \
    $$POVRAY/source/backend/lighting/photonstrategytask.cpp \
    $$POVRAY/source/backend/povray.cpp \
    $$POVRAY/source/backend/render/radiositytask.cpp \
    $$POVRAY/source/backend/render/rendertask.cpp \
    $$POVRAY/source/backend/render/tracetask.cpp \
    $$POVRAY/source/backend/scene/backendscenedata.cpp \
    $$POVRAY/source/backend/scene/view.cpp \
    $$POVRAY/source/backend/scene/viewthreaddata.cpp \
    $$POVRAY/source/backend/support/task.cpp \
    $$POVRAY/source/backend/support/taskqueue.cpp \
    $$POVRAY/source/base/animation/animation.cpp \
    $$POVRAY/source/base/animation/moov.cpp \
    $$POVRAY/source/base/colour.cpp \
    $$POVRAY/source/base/data/bluenoise64a.cpp \
    $$POVRAY/source/base/fileinputoutput.cpp \
    $$POVRAY/source/base/filesystem.cpp \
    $$POVRAY/source/base/fileutil.cpp \
    $$POVRAY/source/base/font/crystal.cpp \
    $$POVRAY/source/base/font/cyrvetic.cpp \
    $$POVRAY/source/base/font/povlogo.cpp \
    $$POVRAY/source/base/font/timrom.cpp \
    $$POVRAY/source/base/image/bmp.cpp \
    $$POVRAY/source/base/image/colourspace.cpp \
    $$POVRAY/source/base/image/dither.cpp \
    $$POVRAY/source/base/image/encoding.cpp \
    $$POVRAY/source/base/image/gif.cpp \
    $$POVRAY/source/base/image/gifdecod.cpp \
    $$POVRAY/source/base/image/hdr.cpp \
    $$POVRAY/source/base/image/iff.cpp \
    $$POVRAY/source/base/image/image.cpp \
    $$POVRAY/source/base/image/jpeg.cpp \
    $$POVRAY/source/base/image/metadata.cpp \
    $$POVRAY/source/base/image/openexr.cpp \
    $$POVRAY/source/base/image/png.cpp \
    $$POVRAY/source/base/image/ppm.cpp \
    $$POVRAY/source/base/image/targa.cpp \
    $$POVRAY/source/base/image/tiff.cpp \
    $$POVRAY/source/base/mathutil.cpp \
    $$POVRAY/source/base/messenger.cpp \
    $$POVRAY/source/base/path.cpp \
    $$POVRAY/source/base/platformbase.cpp \
    $$POVRAY/source/base/pov_err.cpp \
    $$POVRAY/source/base/pov_mem.cpp \
    $$POVRAY/source/base/stringutilities.cpp \
    $$POVRAY/source/base/textstream.cpp \
    $$POVRAY/source/base/textstreambuffer.cpp \
    $$POVRAY/source/base/timer.cpp \
    $$POVRAY/source/core/bounding/bounding.cpp \
    $$POVRAY/source/core/bounding/boundingbox.cpp \
    $$POVRAY/source/core/bounding/boundingcylinder.cpp \
    $$POVRAY/source/core/bounding/boundingsphere.cpp \
    $$POVRAY/source/core/bounding/bsptree.cpp \
    $$POVRAY/source/core/colour/spectral.cpp \
    $$POVRAY/source/core/lighting/lightgroup.cpp \
    $$POVRAY/source/core/lighting/lightsource.cpp \
    $$POVRAY/source/core/lighting/photons.cpp \
    $$POVRAY/source/core/lighting/radiosity.cpp \
    $$POVRAY/source/core/lighting/subsurface.cpp \
    $$POVRAY/source/core/material/blendmap.cpp \
    $$POVRAY/source/core/material/interior.cpp \
    $$POVRAY/source/core/material/media.cpp \
    $$POVRAY/source/core/material/noise.cpp \
    $$POVRAY/source/core/material/normal.cpp \
    $$POVRAY/source/core/material/pattern.cpp \
    $$POVRAY/source/core/material/pigment.cpp \
    $$PWD/portablenoise_shim.cpp \
    $$POVRAY/source/core/material/texture.cpp \
    $$POVRAY/source/core/material/warp.cpp \
    $$POVRAY/source/core/math/chi2.cpp \
    $$POVRAY/source/core/math/hypercomplex.cpp \
    $$POVRAY/source/core/math/jitter.cpp \
    $$POVRAY/source/core/math/matrix.cpp \
    $$POVRAY/source/core/math/polynomialsolver.cpp \
    $$POVRAY/source/core/math/quaternion.cpp \
    $$POVRAY/source/core/math/randcosweighted.cpp \
    $$POVRAY/source/core/math/randomsequence.cpp \
    $$POVRAY/source/core/math/spline.cpp \
    $$POVRAY/source/core/math/vector.cpp \
    $$POVRAY/source/core/render/ray.cpp \
    $$POVRAY/source/core/render/trace.cpp \
    $$POVRAY/source/core/render/tracepixel.cpp \
    $$POVRAY/source/core/scene/atmosphere.cpp \
    $$POVRAY/source/core/scene/camera.cpp \
    $$POVRAY/source/core/scene/object.cpp \
    $$POVRAY/source/core/scene/scenedata.cpp \
    $$POVRAY/source/core/scene/tracethreaddata.cpp \
    $$POVRAY/source/core/shape/bezier.cpp \
    $$POVRAY/source/core/shape/blob.cpp \
    $$POVRAY/source/core/shape/box.cpp \
    $$POVRAY/source/core/shape/cone.cpp \
    $$POVRAY/source/core/shape/csg.cpp \
    $$POVRAY/source/core/shape/disc.cpp \
    $$POVRAY/source/core/shape/fractal.cpp \
    $$POVRAY/source/core/shape/heightfield.cpp \
    $$POVRAY/source/core/shape/isosurface.cpp \
    $$POVRAY/source/core/shape/lathe.cpp \
    $$POVRAY/source/core/shape/lemon.cpp \
    $$POVRAY/source/core/shape/mesh.cpp \
    $$POVRAY/source/core/shape/ovus.cpp \
    $$POVRAY/source/core/shape/parametric.cpp \
    $$POVRAY/source/core/shape/plane.cpp \
    $$POVRAY/source/core/shape/polygon.cpp \
    $$POVRAY/source/core/shape/polynomial.cpp \
    $$POVRAY/source/core/shape/prism.cpp \
    $$POVRAY/source/core/shape/quadric.cpp \
    $$POVRAY/source/core/shape/sor.cpp \
    $$POVRAY/source/core/shape/sphere.cpp \
    $$POVRAY/source/core/shape/spheresweep.cpp \
    $$POVRAY/source/core/shape/superellipsoid.cpp \
    $$POVRAY/source/core/shape/torus.cpp \
    $$POVRAY/source/core/shape/triangle.cpp \
    $$POVRAY/source/core/shape/truetype.cpp \
    $$POVRAY/source/core/support/cracklecache.cpp \
    $$POVRAY/source/core/support/imageutil.cpp \
    $$POVRAY/source/core/support/octree.cpp \
    $$POVRAY/source/core/support/statisticids.cpp \
    $$POVRAY/source/core/support/statistics.cpp \
    $$POVRAY/source/frontend/animationprocessing.cpp \
    $$POVRAY/source/frontend/console.cpp \
    $$POVRAY/source/frontend/display.cpp \
    $$POVRAY/source/frontend/filemessagehandler.cpp \
    $$POVRAY/source/frontend/imagemessagehandler.cpp \
    $$POVRAY/source/frontend/imageprocessing.cpp \
    $$POVRAY/source/frontend/parsermessagehandler.cpp \
    $$POVRAY/source/frontend/processoptions.cpp \
    $$POVRAY/source/frontend/processrenderoptions.cpp \
    $$POVRAY/source/frontend/renderfrontend.cpp \
    $$POVRAY/source/frontend/rendermessagehandler.cpp \
    $$POVRAY/source/frontend/shelloutprocessing.cpp \
    $$POVRAY/source/parser/fncode.cpp \
    $$POVRAY/source/parser/parser.cpp \
    $$POVRAY/source/parser/parser_expressions.cpp \
    $$POVRAY/source/parser/parser_functions.cpp \
    $$POVRAY/source/parser/parser_functions_utilities.cpp \
    $$POVRAY/source/parser/parser_materials.cpp \
    $$POVRAY/source/parser/parser_obj.cpp \
    $$POVRAY/source/parser/parser_strings.cpp \
    $$POVRAY/source/parser/parser_tokenizer.cpp \
    $$POVRAY/source/parser/parsertypes.cpp \
    $$POVRAY/source/parser/rawtokenizer.cpp \
    $$POVRAY/source/parser/reservedwords.cpp \
    $$POVRAY/source/parser/scanner.cpp \
    $$POVRAY/source/parser/symboltable.cpp \
    $$PWD/povms_c_shim.cpp \
    $$POVRAY/source/povms/povms.cpp \
    $$POVRAY/source/povms/povmscpp.cpp \
    $$POVRAY/source/povms/povmsutil.cpp \
    $$POVRAY/source/vm/fnintern.cpp \
    $$POVRAY/source/vm/fnpovfpu.cpp \
    $$POVRAY/vfe/vfe.cpp \
    $$POVRAY/vfe/vfecontrol.cpp \
    $$POVRAY/vfe/vfedisplay.cpp \
    $$POVRAY/vfe/vfepovms.cpp \
    $$POVRAY/vfe/vfesession.cpp \
    $$POVRAY/vfe/unix/vfeplatform.cpp \
    $$POVRAY/vfe/unix/unixoptions.cpp
