#############################################################################
# Makefile for building: physics
# Generated by qmake (2.01a) (Qt 4.6.2) on: So. Jan 30 12:18:27 2011
# Project:  physics.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile physics.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -I/usr/include/bullet -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -I/usr/include/bullet -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Iroboop/include -Iroboop/newmat -Iroboop/source -I/usr/X11R6/include -I.moc -I.ui
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lspnav -lqglviewer-qt4 -lglut -l3ds -lroboop -lnewmat -Lroboop -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		palette.cpp \
		viewer.cpp \
		object.cpp \
		cube.cpp \
		sphere.cpp \
		plane.cpp \
		cylinder.cpp \
		mesh3ds.cpp \
		rm.cpp \
		collisionfilter.cpp \
		rm1.cpp \
		cubeaxes.cpp \
		gui.cpp \
		cmdline.cpp \
		dice.cpp \
		spacenavigator.cpp \
		spacenavigatorevent.cpp \
		SpaceNavigatorCam.cpp .moc/moc_viewer.cpp \
		.moc/moc_gui.cpp \
		.moc/moc_cmdline.cpp \
		.moc/moc_spacenavigator.cpp \
		.moc/moc_SpaceNavigatorCam.cpp
OBJECTS       = .obj/main.o \
		.obj/palette.o \
		.obj/viewer.o \
		.obj/object.o \
		.obj/cube.o \
		.obj/sphere.o \
		.obj/plane.o \
		.obj/cylinder.o \
		.obj/mesh3ds.o \
		.obj/rm.o \
		.obj/collisionfilter.o \
		.obj/rm1.o \
		.obj/cubeaxes.o \
		.obj/gui.o \
		.obj/cmdline.o \
		.obj/dice.o \
		.obj/spacenavigator.o \
		.obj/spacenavigatorevent.o \
		.obj/SpaceNavigatorCam.o \
		.obj/moc_viewer.o \
		.obj/moc_gui.o \
		.obj/moc_cmdline.o \
		.obj/moc_spacenavigator.o \
		.obj/moc_SpaceNavigatorCam.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		physics.pro
QMAKE_TARGET  = physics
DESTDIR       = 
TARGET        = physics

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .ui/ui_gui.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: physics.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libqglviewer-qt4.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile physics.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libqglviewer-qt4.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile physics.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/physics1.0.0 || $(MKDIR) .obj/physics1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/physics1.0.0/ && $(COPY_FILE) --parents palette.h viewer.h object.h cube.h sphere.h plane.h cylinder.h mesh3ds.h rm.h collisionfilter.h rm1.h cubeaxes.h gui.h cmdline.h dice.h spacenavigator.h spacenavigatorevent.cpp SpaceNavigatorCam.h .obj/physics1.0.0/ && $(COPY_FILE) --parents main.cpp palette.cpp viewer.cpp object.cpp cube.cpp sphere.cpp plane.cpp cylinder.cpp mesh3ds.cpp rm.cpp collisionfilter.cpp rm1.cpp cubeaxes.cpp gui.cpp cmdline.cpp dice.cpp spacenavigator.cpp spacenavigatorevent.cpp SpaceNavigatorCam.cpp .obj/physics1.0.0/ && $(COPY_FILE) --parents gui.ui .obj/physics1.0.0/ && (cd `dirname .obj/physics1.0.0` && $(TAR) physics1.0.0.tar physics1.0.0 && $(COMPRESS) physics1.0.0.tar) && $(MOVE) `dirname .obj/physics1.0.0`/physics1.0.0.tar.gz . && $(DEL_FILE) -r .obj/physics1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/moc_viewer.cpp .moc/moc_gui.cpp .moc/moc_cmdline.cpp .moc/moc_spacenavigator.cpp .moc/moc_SpaceNavigatorCam.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_viewer.cpp .moc/moc_gui.cpp .moc/moc_cmdline.cpp .moc/moc_spacenavigator.cpp .moc/moc_SpaceNavigatorCam.cpp
.moc/moc_viewer.cpp: rm1.h \
		object.h \
		cube.h \
		cubeaxes.h \
		spacenavigator.h \
		spacenavigatorevent.h \
		viewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) viewer.h -o .moc/moc_viewer.cpp

.moc/moc_gui.cpp: .ui/ui_gui.h \
		viewer.h \
		rm1.h \
		object.h \
		cube.h \
		cubeaxes.h \
		spacenavigator.h \
		spacenavigatorevent.h \
		cmdline.h \
		gui.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui.h -o .moc/moc_gui.cpp

.moc/moc_cmdline.cpp: cmdline.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cmdline.h -o .moc/moc_cmdline.cpp

.moc/moc_spacenavigator.cpp: spacenavigatorevent.h \
		spacenavigator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spacenavigator.h -o .moc/moc_spacenavigator.cpp

.moc/moc_SpaceNavigatorCam.cpp: spacenavigatorevent.h \
		SpaceNavigatorCam.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SpaceNavigatorCam.h -o .moc/moc_SpaceNavigatorCam.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .ui/ui_gui.h
compiler_uic_clean:
	-$(DEL_FILE) .ui/ui_gui.h
.ui/ui_gui.h: gui.ui
	/usr/bin/uic-qt4 gui.ui -o .ui/ui_gui.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

.obj/main.o: main.cpp gui.h \
		.ui/ui_gui.h \
		viewer.h \
		rm1.h \
		object.h \
		cube.h \
		cubeaxes.h \
		spacenavigator.h \
		spacenavigatorevent.h \
		cmdline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/palette.o: palette.cpp palette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/palette.o palette.cpp

.obj/viewer.o: viewer.cpp viewer.h \
		rm1.h \
		object.h \
		cube.h \
		cubeaxes.h \
		spacenavigator.h \
		spacenavigatorevent.h \
		collisionfilter.h \
		plane.h \
		sphere.h \
		cylinder.h \
		mesh3ds.h \
		rm.h \
		palette.h \
		dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/viewer.o viewer.cpp

.obj/object.o: object.cpp object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/object.o object.cpp

.obj/cube.o: cube.cpp cube.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cube.o cube.cpp

.obj/sphere.o: sphere.cpp sphere.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/sphere.o sphere.cpp

.obj/plane.o: plane.cpp plane.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/plane.o plane.cpp

.obj/cylinder.o: cylinder.cpp cylinder.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cylinder.o cylinder.cpp

.obj/mesh3ds.o: mesh3ds.cpp mesh3ds.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/mesh3ds.o mesh3ds.cpp

.obj/rm.o: rm.cpp rm.h \
		object.h \
		cube.h \
		mesh3ds.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/rm.o rm.cpp

.obj/collisionfilter.o: collisionfilter.cpp collisionfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/collisionfilter.o collisionfilter.cpp

.obj/rm1.o: rm1.cpp rm1.h \
		object.h \
		cube.h \
		cubeaxes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/rm1.o rm1.cpp

.obj/cubeaxes.o: cubeaxes.cpp cubeaxes.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cubeaxes.o cubeaxes.cpp

.obj/gui.o: gui.cpp gui.h \
		.ui/ui_gui.h \
		viewer.h \
		rm1.h \
		object.h \
		cube.h \
		cubeaxes.h \
		spacenavigator.h \
		spacenavigatorevent.h \
		cmdline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/gui.o gui.cpp

.obj/cmdline.o: cmdline.cpp cmdline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/cmdline.o cmdline.cpp

.obj/dice.o: dice.cpp dice.h \
		object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/dice.o dice.cpp

.obj/spacenavigator.o: spacenavigator.cpp spacenavigator.h \
		spacenavigatorevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/spacenavigator.o spacenavigator.cpp

.obj/spacenavigatorevent.o: spacenavigatorevent.cpp spacenavigatorevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/spacenavigatorevent.o spacenavigatorevent.cpp

.obj/SpaceNavigatorCam.o: SpaceNavigatorCam.cpp SpaceNavigatorCam.h \
		spacenavigatorevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/SpaceNavigatorCam.o SpaceNavigatorCam.cpp

.obj/moc_viewer.o: .moc/moc_viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_viewer.o .moc/moc_viewer.cpp

.obj/moc_gui.o: .moc/moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_gui.o .moc/moc_gui.cpp

.obj/moc_cmdline.o: .moc/moc_cmdline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_cmdline.o .moc/moc_cmdline.cpp

.obj/moc_spacenavigator.o: .moc/moc_spacenavigator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_spacenavigator.o .moc/moc_spacenavigator.cpp

.obj/moc_SpaceNavigatorCam.o: .moc/moc_SpaceNavigatorCam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_SpaceNavigatorCam.o .moc/moc_SpaceNavigatorCam.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

