#ifndef OPENSCAD_H
#define OPENSCAD_H

/**
 * @file openscad.h
 * @brief A mesh generated by running OpenSCAD on a script.
 */

#ifdef HAS_LIB_ASSIMP

#include "mesh.h"

#include <QObject>
#include <QProcess>

/**
 * @brief A Mesh whose geometry is produced by OpenSCAD at run time.
 *
 * Takes OpenSCAD source rather than a model file: the source is written to a
 * temporary file, @c openscad is run on it to produce an STL, and the result
 * is loaded through the inherited Mesh machinery. This lets a script describe
 * a solid parametrically and simulate it without an external modelling step.
 *
 * OpenSCAD runs asynchronously, so the object exists before its geometry does.
 * isReady() reports whether it has arrived and stlReady() is emitted when it
 * does.
 */
class OpenSCAD : public Mesh {
  Q_OBJECT
public:
  /**
   * @brief Starts OpenSCAD on some source and builds a mesh from the result.
   * @param sdl          The OpenSCAD source.
   * @param mass         Mass for the resulting body; applied once the geometry
   *                     has been loaded.
   * @param centerOfMass Whether to shift the mesh so its centre of mass is at
   *                     the body's origin.
   */
  explicit OpenSCAD(QString sdl, btScalar mass, bool centerOfMass = true);

  /**
   * @brief Registers the OpenSCAD class with a Lua state.
   * @param s The Lua state to register in.
   */
  static void luaBind(lua_State *s);

  /**
   * @brief Returns the object's type name.
   * @return The literal @c "OpenSCAD".
   */
  virtual QString toString() const;

  /**
   * @brief Reports whether the geometry has been generated and loaded.
   * @return True once OpenSCAD has finished and the STL was read.
   */
  bool isReady() const;

signals:
  /**
   * @brief Emitted once the generated geometry has been loaded.
   */
  void stlReady();

private:
  /**
   * @brief Shows the busy indicator while OpenSCAD runs.
   */
  void showProgressBar();

  /**
   * @brief Hides the busy indicator once OpenSCAD has finished.
   */
  void hideProgressBar();

  QString sdl;            ///< The OpenSCAD source to compile.
  QProcess *m_process;    ///< The running @c openscad process.
  QString m_stlfile;      ///< Path of the STL it writes.
  btScalar m_pendingMass; ///< Mass to apply once the geometry is loaded.
  bool m_centerOfMass;    ///< Whether to recentre the mesh on its centre of
                          ///< mass when loading it.
  bool m_stlReady;        ///< True once the STL has been loaded.
};

#endif // HAS_LIB_ASSIMP

#endif // OPENSCAD_H
