; Geneva Drive v 202608.1

width = 720
height = 960

sampling_method = 3
antialias_gamma = 1
antialias_threshold = 0.01
antialias_confidence = 0.9995
jitter = off
quality = 11

initial_frame = 0
final_frame = 719
cyclic_animation = on

display = on
pause_when_done = off
work_threads = 6

input_file_name = gdrx.pov

verbose = on
all_file = on
output_file_name = gdr_

